from upgenius.network.downloader._requests import RequestsDownloader
from upgenius.network.downloader._requests import RequestsSessionDownloader
from upgenius.network.downloader._selenium import SeleniumDownloader
from upgenius.network.downloader._playwright import PlaywrightDownloader
